### ISSUE TITLE
Revert to 5.x and start over. 

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#108]
I suggest you revert to the 5.x version and start over making 6.x. The import from 5.x should be optional. You could provide a backup feature, then attempt the import. If it does not work then you can revert. 6.x would start cleanly on its own.
Sometime backwards compatible is compatible with backwards.

**Comment by lscheffler** [comment]
GF 6 is not data compatible to GF 5. This happens if one change functionality.    
There is an update that might fail, why ever, on some machines.   
There is a backup of all GF 5 data in folder Home(7)+"GoFish_Backup"   
If you need to revert to GF 5, just move the backup files one level down to home(7)   
If you need a clean GF 6, remove all GF*.* stuff from HOME(7) including "GoFish_" folder (possibly w/o the backup), start GF 6    

If you like to start over with GF 6, feel free to fork from 726d4aa4471df64366c5674d7f73 and go ahead.

**Comment by Jimrnelson** [comment]
@myearwood1 @lscheffler 

Reverting to GF5 requires somewhat more than correcting the settings in Home(7).

The App itself (for either V5 or V6) lives in folder `_screen.cThorFolder + 'Tools\Apps\Gofish5'`.

You would need to restore that folder from backup.

If using Thor's Check For Updates, you will also want to mark GoFish as 'Never Update'.

Note that with the current design V5 and V6 cannot coexist in Thor.

**Comment by myearwood1** [comment]
My point exactly. The approach to automatically upgrade broke my setup and others. I suggest you should have allowed the user to trigger the upgrade and restore it for them if it failed. If it worked, no harm to anyone. If it failed, GoFish would restore. GoFish6 would be a new standalone thing with an optional import from 5 without breaking either.

**Comment by Jimrnelson** [comment]
Well, Mike, the eggs are already scrambled.  

Too late to make suggestions about how the upgrade might have been handled differently.

**Comment by lscheffler** [comment]
> @myearwood1 @lscheffler
> 
> Reverting to GF5 requires somewhat more than correcting the settings in Home(7).
> 
> The App itself (for either V5 or V6) lives in folder `_screen.cThorFolder + 'Tools\Apps\Gofish5'`.
> 
> You would need to restore that folder from backup.
> 
> If using Thor's Check For Updates, you will also want to mark GoFish as 'Never Update'.
> 
> Note that with the current design V5 and V6 cannot coexist in Thor.

@Jimrnelson 
Aside the stuff in Home(7), wouldn't it be enough to set CFU to *Never update*, gather GF 5 into some folder and run it? You end up with a *GoFish5* entry to Thor Tools because of the way GF forces itself into Thor. The latest GF 6should do a *GoFish* without 5.   

It looks like that on my comp - I have GF 5 to test against. But this is an academic.

**Comment by myearwood1** [comment]
This is not religion. This is software. There is always room for improvement. It is never too late to fix bugs. You should know never to scramble someone else's eggs. I renamed the new app so it would not interfere with the existing app. If this is version 6, why is this code in gofish.prg?
lnSys16 = 1
DO WHILE !LOWER(JUSTFNAME(SYS(16,m.lnSys16)))=="gofish5.app"
   lnSys16 = m.lnSys16+1
ENDDO

The programmers I inherited this system from did not upgrade to 9. I cannot run GoFish as part of my environment. 
I got it working.

I removed the previous home(7) gofish5 folders.

I have to start GoFish with a shortcut to vfp9. The starting folder is Desktop\MyStuff\GoFish6\source

There is a special config file -cconfiggofish6.dev
title=GOFISH6
resource=off
mvcount=32000
command=do setupgofish6

I put setupgofish6.prg in your source folder.
SET STATUS BAR OFF
SET TALK OFF
SET ECHO OFF
IF WVISIBLE("Properties")
	RELEASE WINDOWS "Properties"
ENDIF
if wvisible("COMMAND")
	release windows "Command"
endif
DO GOFISH6.APP

**Comment by myearwood1** [comment]
It is never too late to change anything in software.

**Comment by Jimrnelson** [comment]
> It is never too late to change anything in software.

When the change is to be made by a volunteer, and the time necessary to make that change is deemed excessive by them, it can indeed be too late.

**Comment by myearwood1** [comment]
and if that's how you entice volunteers, you can see why I don't bother anymore.

**Comment by Jimrnelson** [comment]
@lscheffler 

> Aside the stuff in Home(7), wouldn't it be enough to set CFU to _Never update_, gather GF 5 into some folder and run it? You end up with a _GoFish5_ entry to Thor Tools because of the way GF forces itself into Thor. The latest GF 6should do a _GoFish_ without 5.

An individual could do this manually, for themselves, but it would be tricky to get the Thor tools to work.  I have tried and realized that it can be done, although I could not give you all the steps.  There'd be some related fun having to do with hot keys for GF and also menu entries, if any.

Getting it to work for all users (by way of CFU) so that they could have both GF5 and GF6 would be quite a large hurdle.  I'm not sure how many would care.

**Comment by lscheffler** [comment]
@Jimrnelson As a Syrian friend told me once: The Qur'an allows you to have several wives. But you are not forced to do it.
One can do this, but I would nobody encourage to, it's not set up this way. And it was more like how to go back in case, supporting to come out of a struggle as good as possible.    

There is no problem to go back to the GF5, the commit is provided, and it requires to figure out a folder and unpack some files. Should be possible for a dev to do. If there are questions how to do this, on can ask for help I'm sure you or me would provide.

**Comment by lscheffler** [comment]
@myearwood1 your approach with the external call sounds good.   
Use *tcInitialSource* parameter of GoFish to set your recent folder / project as initial scope, or *Restore previous search results on startup* option to restore your scope.   
You might also try to clone this repo, compile in VFP8 and check if is running. I'm not really sure about the use of *new* commands - VFP 9 is that old, I don't remember the changes and use them without thinking.

**Comment by Jimrnelson** [comment]
> You might also try to clone this repo, compile in VFP8 and check if is running.

GF uses anchors, introduced in VFP9, so compiling in VFP8 will not work.
