### ISSUE TITLE
upgrading to 6.

### ISSUE THREAD

**Issue by myearwood1** [VFPX/GoFish#112]
1 - by the time I encountered the crash, my gofish5 data was unusable.
2 - I removed 6 and started 5. It created a new set of 5 data.
3 - I backed that up.
4 - I started 6. It upgraded without problems.
5 - I am unable to provide you with files.
6 - Had you anticipated this crash - you would have backed up the original files for the user, installed your new files, and made importing the old ones optional. You gambled on doing it the wrong way and now only defend doing it the wrong way. Hopefully, another user whose eggs your gamble is scrambling will try to help, but they will not be able to because by the time they find it fails, there is nothing to send you.

You have no choice but to fully backup the users' "sensitive - not sensible" files before you attempt to upgrade them, in the hopes it fails.

Furthermore, when you give your initial warning, use an edit box or something, so users can, at least, copy and paste your message.

Good luck.

**Comment by lscheffler** [comment]
Dear Mr. Yearwood,  I've done myself the fun and read some of your elegies on LevelExtreme today, for the fun of it. Just to let you know where I stand.

You as the one who **Showed the Fox to Microsoft**, should know that a simple "CTRL+C" will copy the content of a Messagebox to the clipboard.

Only. The warning is a form, and the text is within an editbox. It has the focus on start. A cursor is blinking. A simple CTRL+A CTRL+C would have done. I thought somebody with your unseen skills, naming other programmers **crappy coders** just by a whim, would have noticed this on first glance.

Sure I hope somebody with a bit of time and programming skills runs into it and would help me to see what is going wrong - since I can not reproduce. I do not know why it happens, I have even set foxuser and the whole registry to an other users settings, running this users backup - and it still works like a charm on my comp. But this is only me little unskilled code monkey.

**Comment by myearwood1** [comment]
Your first response to me on this thread was rude and ignorant. All I did was suggest a better way forward. You still won't take the advice. Typical. Even Jim Nelson's fighting to keep your bad practices afloat was rude and ignorant. It is the fact that for many, many years I put up with rude, ignorant, abusive, and even criminal people, with no one telling them to stop, even when others were harmed by them, that showed me I only have to be within the letter of the law to this community. It is you that needs my help, and you have given me no reason to help, as usual.

There are crappy coders. It is not a whim, it is a fact. I never said everyone is a crappy coder. You can see crappy code even and unfortunately in GoFish. I gave a real working fix when someone crashed into crappy code. My fix was not included even though others confirmed it was correct. I can only assume further disrespect and abuse as the cause. The same person crashed into the same bug much later. That was ridiculous.

You can see the result of bad practices in what you have encountered. There are sickos in this community. I never said everyone is. There are criminals in this community. I never said everyone is. I have named those where I have actual proof of their abuse of me and others, yet nothing changes. Instead, I am accused of abuse and the abuse and derision given to me by so many through the years is ignored and continues right here. There is room for improvement in EVERYTHING, unless you're only willing to say "the eggs are scrambled" and live with it. I attempted to reproduce the bug FOR YOU. I don't know why I wasted my time.

You crashed headlong into this bug because you are less skilled than you think you are. You don't know why it happens. I told you why. Your approach of not making backups and not protecting your users is the GAMBLE you lost. I and other users got burned by you and the best you can do is put up a warning. I did not notice it was a message box. I was busy trying to undo the mess you made for me. 

You, and far too many, think yourself some kind of coding god. You think you were kidding in the attached, but it is the kind of juvenile insulting behavior I protest and you seem not to have improved. You did not have my experience even then of dealing with the problems caused by having to work on the crappy code of so many "programmers" that you dismiss valuable input. That too is typical of "programmers".

 ![image](https://github.com/VFPX/GoFish/assets/5750619/03361b22-0ad3-423c-8bdf-fa685d67ac4a)

You cannot listen to good advice, so you got into the very mess you are in now. Maybe you should go read the book "The Inmates Are Running the Asylum"

As I said, good luck.

**Comment by lscheffler** [comment]
Ah. Publishing postings out of a private forum into open without permission. Not from one of the participants, not from the owner of the forum. Not just quoting, screenshots. How poor. But typical you.

Your problem is simply that you think your advice is in any form superior, or that something you have learned will never change. You can not see others positions, this is nothing new, and if one will not praise your wisdom, you start to blame your opponent. Something visible for half a decade at least. Guess why one is so happy if one only read your name. I'm not very sorry to be triggered by it. 

My first reaction to your first post was polite, compared by my instant feelings, I even offered help fixing the havoc I know not better to solve. While knowing better. I see my mistake.

Btw, a real guru would not have told others how to proceed with stuff dead for months, he would have looked up why the error happens and how to avoid it. I clearly please everybody to do so. Thanks for the help. I'm sure I could fix this - if only I could raise the error in the first place. 

\<°(((\><

**Comment by myearwood1** [comment]
I have fixed errors in this "product" before and the previous people failed to integrate it, which was insulting. The difference between you and me, is I provide proof to back up my claims and do not violate GitHub's policy against posting libelous material. You have been reported for your illegal activity. Have a good day.

**Comment by lscheffler** [comment]
Deleted a message with a picture out of private forum. Locked conversation
