### ISSUE TITLE
Desktop Windows on multiple screen setup

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#12]
## 📝 Position of instantiation

While it is nice to have the forms desktop, it's odd to open them on unexpected screen. The Forms open somewhere near 0,0 of my combined screens - what is out of my focus. If stored there, it might be OK

The forms shout open relative to the upper left corner of the screen where the active form is open, if not stored otherwise.

Addidionally, if the main form is not Desktop, the child forms like settings should follow that.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by DougHennig** [comment]
I am not sure I understand: when I run GoFish, the main and child forms open in the exact location they were at the last time I used them (for me, it is on my second monitor).

As for the child forms, Matt (or Peter) designed it so they are always Desktop. Since a form can't be se to Desktop at runtime, having both desktop and non-desktop child form would mean creating separate child form classes for each type and then instantiating the correct one. I am not sure that is worth the effort, but if someone wants to do that, they can.

**Comment by lscheffler** [comment]
But *only* after one moved it. The very first run is odd. **I** would expect the form open on the monitor I'm on. I know, a lot of work for nearly nothing. Just let it open for a while. Possibly I found fun on it, or somebody added likes.

**Comment by lscheffler** [comment]
@DougHennig, I found the reason to this while fixing #29, I guess I know how to fix it as well.

**Comment by DougHennig** [comment]
OK, great.
