### ISSUE TITLE
GoFish6 should not automatic update from GoFish5

### ISSUE THREAD

**Issue by lscheffler** [VFPX/GoFish#151]
## 📝 Provide a description of the new feature

Out of discussion #145

GoFish6 automatically updates settings and results GoFish5.
- Make the Update optional
- In special, if already a GoFish6 setting exists, to allow GF5 parallel to GF6
- Store the result.

---
If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Lutz --

It's unclear to me what you are trying to achieve here.  Can you elaborate a little?

Are you now supporting the old version GoFish5 (as distinct fromGoFishClassic)?  If so, I have to wonder why you are bothering to do so.

Are you aware of users who use both versions?  I would think most/maybe all users stick with one or the other.

**Comment by lscheffler** [comment]
Jim    
Right now, the GF 6 checks on startup, if the settings of GF5 exists in Home(7). If found, it will check for settings of GF6, create backups of both GF5 and GF6 and imports GF5 to GF6. Then it removes the GF5 settings.

So every time somebody runs GF5, then GF6:
- it rereads the settings, starting GF6 with those
- next start of GF5 runs from scratch

For that you can not have both on the same comp. (Why ever, but it is not up to me to decide this).

So asking the user to update, allow to stop this, and also allow to start GF6 without the GF5 stuff, what gave some people problems I have no idea to solve.

**Comment by Jimrnelson** [comment]
Lutz --

That is not the behavior I am seeing.

I just ran GFClassic, closed VFP, ran GF6, closed VFP, ran GFClassic again.

GFClassic did _not_ start from scratch.  It had exactly the same settings it had before.

My understanding, consistent with the behavior I have seen, is that once you have run GF6 once and it modifies / creates its places for settings, etc, it never does that again.

Of course, one can't run GFClassic and GF6 in the same session (problems with SET LIB or something as I recall).

**Comment by lscheffler** [comment]
Never mind. This was the behaviour I stopped with in June. I check it (because of that the issue is self-assigned). This is more a reminder to myself.

If it works as expected, fine.

**Comment by lscheffler** [comment]
@Jimrnelson I have checked, you are right, it ignores GF5, if once updated, IOW "GoFish_" directory exists in HOME(7)   

So what remains,
- is that the GF5 files will be moved to backup on initial update
- and that the initial Update will be forced.

What's your idea on this?

**Comment by Jimrnelson** [comment]
Lutz --

I have never understood why you choose to move the GF5 settings files when moving to GF6.  Since you're not referencing them in any way, I see no reason to do anything but ignore them.

I did find it quite annoying when installing GF6 that my GF5 settings files were gone.  I needed them because I had to go back to GF5 because of GF6 installation issues.   Restoring the code was obvious, but restoring the settings was not.

BTW (too late for me), I would have wanted to be asked whether GF6 installation moved all my search history files into the new format.  Since I rarely use search history (same day only), I would have been saved a lot of hassle if I could have just skipped this step.  (Eventually what I resorted to was to simply remove all of my search history by hand)

I'm not sure what you're asking in your second bullet point.  If going to GF6. don't you have to force it?

**Comment by lscheffler** [comment]
Jim

Your (old) GF5 Settings / History could still exist in Home(7) + "GoFish_Backup_*" folder. The prefacing screen is about it, and I think I mentioned it somewhere in the docu. It's just moving the whole folder one level up. 

GF6 uses as many settings as possible from GF5 (except the update-bug I never was able to reproduce prevents this), and the history of GF5. Basically it uses
- a different structure for the histories (permanent database+table instead of creating a cursor from the files on the fly)
- a folder dedicated to GoFish to store the GoFish stuff rather then a lot of files in HOME(7)
- The settings storage is not altered in the way it works, just on a different place, and more options

Why I decided to move them?   
I'm not a fan of having both GF5 and GF6 on the same comp. Pretty fine to create havoc if using PATH, or running subsequently in the same session. So it was just an update, and the files of GF 5 had no use any more. I later backed them up, due to this update bug.

> I'm not sure what you're asking in your second bullet point. If going to GF6. don't you have to force it?

As we have learned, it does not care about existing GF5 settings later on, And it will initialize without any GF5 stuff. So it would simply instantiate a vanilla folder and run vanilla GF6. Just like
- No GF5 files found -> initialize vanilla GF6
- GF5 files found, ask to copy settings
  - if *no*, create vanilla GF6
  - if *yes*, copy to GF6 and ask if the GF5 should be removed
    - if *no*, do nothing
    - if *yes*, move to backup folder

Or ask to remove the GF5 stuff if it is used for GF6 or not.

---
>  Since I rarely use search history (same day only), ...

There is a setting that allows to auto clean up old stuff somewhere in options. I guess *Janitor*?

---
Long stuff short, do I get it right, you say it should ask 
- if it should update
- if it should remove GF5

**Comment by Jimrnelson** [comment]
Lutz:

> I'm not a fan of having both GF5 and GF6 on the same comp. Pretty fine to create havoc if using PATH, or running subsequently in the same session.

I certainly understand your preference not to have GF5 and GF6 on the same computer.  That is different than imposing that same restriction on all GF users.

When GF6 has finally settled, it would be fine to rely on having only one version available.  Until that time, I think it would have been appropriate to have planned on having both the new and old versions available, as insurance against the time when GF6 breaks.  This is exactly what we did when we moved from GF4 to GF5.

>  So it was just an update, and the files of GF 5 had no use any more. I later backed them up, due to this update bug.

This statement would be true only if GF6 was 100% reliable.  When it is not, users should have been provided a path to easily revert to the old reliable GF5. (Personal note: I have not found it reliable yet and at least some others have reported the same, which is why GoFishClassic was resurrected.)

*** 

My thought on this is that the user cannot possibly know when upgrading internally to GF6 whether they want to keep the old GF5 settings.  I suggest you protect them by assuming they _might_, so you don't give them a chance to blunder.

The only question I would ask would be if they want to migrate their old search history into the new format.

Then, you provide a button (somewhere) that would allow them later to remove the GF5 settings, at the time of their choosing.

 ***

> Since I rarely use search history (same day only), ...

>> There is a setting that allows to auto clean up old stuff somewhere in options. I guess Janitor?

Yup, that was actually my idea.  I believe I've got it set to only a few days, but I never pay attention.

**Comment by lscheffler** [comment]
Hi Jim,

I count the user as developers, not KCI problems. So they should have a little idea what is happening. A remove *GF5 stuff* button somewhere is a lot of bloat, - one need to have code to enable it, checking for the GF5 files, space for the object, etc. A messagebox in the start program, running only when there is no HOME(7)+GoFish_ **AND*** GF5 files folder is less complex by an order of magnitude, and the whole thing is minor. The GF5 data is backed up, and for the huge majority it is / was just *update*.

Only for a very little it was an issue updating, and even that was a Heisenbug. There was no chance to debug it, I simply can not raise it, whatever I try to emulate. What was down to copy registry and foxuser. Also nobody volunteered to look up the reasons on a computer where the problem happens, so I'm helpless with this.    
For those with the bug there was a backup of GF5, simple, neat, and visible. Also it was simple to start vanilla GF6 - it's just removing to GF6 folder. Since the GF5 files where removed, next start will be a vanilla GF6. No GF5 files in HOME(7), no fuzz updating. Simplest way to achieve this solution. No stupid Yes/No dialogues.

So even dialogues like this issue suggests, are a solving a non-problem. I'm sorry that you belong to the few that run into the bug, but again, I-can-not-raise-it. For some users I gathered there GF5 data, fired my GF6 an my comp, and, voilà, it was updated. I tried there data with there foxuser and there registry stuff active, checking all there SET and SYS settings, and I-can-not-raise-it. 
I vote for a computer problem on your side, either active snake oil aka anti virus or memory / disk drive problems. If I was you, I would run HDD / memory check, possibly a deep scanning virus check *from a live system*. Also emulated windows on Apple / LINUX comps create odd problems, there was fancy stuff with Spanish chars in FoxBin2PRG lately.

**Comment by Jimrnelson** [comment]
Implemented in Version 7, released 2024-03-08:

- Upgrading from Version 5 to Version 7 does not affect any of the settings for Version 5, so that Version 5 may still run as before.
- The search history from Version 5 is **not** imported into Version 7.  (Most of the problems upgrading from Version 5 to Version 6 occurred when attempting to import search history.)
