### ISSUE TITLE
Integrate with Project Explorer

### ISSUE THREAD

**Issue by DougHennig** [VFPX/GoFish#154]
One thing I and others like about Project Explorer is that if you edit a VFP binary (form, class, report, etc.) from Project Explorer, it can automatically call FoxBin2PRG or other program to generate the text file when you close the editor. However, if you use GoFish to edit the file, Project Explorer doesn't know about it so the automatic generation doesn't occur.

See https://doughennig.blogspot.com/2019/06/integrating-project-explorer-with.html for a simple change to integrate GoFish with Project Explorer.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by lscheffler** [comment]
@DougHennig    
I'm not really sure about this. I see the use for your approach to handle git (...), but probably the stuff that ProjextExplorer is doing should be done by ProjectExplorer.   

What I have in my mind is that GF checks for PE instances, calls PE and PE EventBind to the appropriate Method and cares about itself.   
GF release all Binds to itself on closing, PE as well.   
PE might check on start for GF too.

So for GF it's just notifying PE and releasing the EventBinding.
All we need on PE is a method to notify about GF, and the declaration of the stuff GF is running internal.   
And wheter or not PE cares at all is a problem of PE.

**Comment by DougHennig** [comment]
Actually, it's much simpler than that. If PE exists, call its EditFile method. Otherwise, do what GF is doing now:

if type('_screen.oProjectExplorers') = 'O' and _screen.oProjectExplorers.Count > 0
    loPE = _screen.oProjectExplorers[1]
    loPE.EditFile(lcFileName, lnLineNo, justfname(lcFileName), lcMethod)
else
* edit the file
endif

**Comment by lscheffler** [comment]
I'm not rejecting, just discussing.    
This was understood.    
But this means that GF must provide the interface to an external tool. My approach is, that each tool cares about itself, by a set of otherwise transparent interfaces.

So GF offers information about interfaces, PE as well, and if PE needs to something when GF does an action, it hooks in. On the same scale there should be something on  PE that tells GF the files in PE - a Method like O or AGetFileList(). Encapsulation. How ever PE is storing the file list now or then, the result of the Method should be the same.    
So, if we once add GF the function to get a scope on a PE instance, we *ask* PE for the files, rather then running a collection or the like.    
Like this, GF will own a method with a defined interface called when editing a file - by something GF defines, not PE.   
We also could use this for replace stuff, so PE gets notified about replaces, possibly even used for AFTER~ and BEFORE~ and PE can take action like a before or after transform / commit. The good is, this code does not need to care about anything on PE - as long as it gives all relevant information.   
Also, I think raising PE for any file, even stuff that does not belong to this instance might not be the best idea. PE could care about this by itself. The scope of the search could be somewhere.

**Comment by DougHennig** [comment]
I agree that a tool shouldn't know anything about another tool. Perhaps GoFish could use a plugin. If a certain PRG exists, that PRG is called instead of using EditSource to edit a file. Then I could create a plugin that would call loPE.EditFile.

**Comment by lscheffler** [comment]
So the tool decides if GF or anything else opens the file? That's a possible way too. This PlugIn is called if found just by it's name, and the return tells GF if it should raise the internal method.

I still like eventbinding more, only it would need a kind of callback to tell GF the delegate will open the file.

---
For the idea of notifying PE about GR-Replace, should we discuss this here or on PE, and if on PE, would you open discussions? it's not really a request from my side. :)

**Comment by DougHennig** [comment]
I don't think event binding would work, because editing the file is executed from GoFish, which PE doesn't know is open, so it doesn't have anything to bind to.

I think this should be straightforward. The code editing a file in GoFish would be something like this:

```
if file('Plugins\EditFilePlugin.prg')
    do Plugins\EditFilePlugin
else
* use existing code e.g. EDITSOURCE
endif
```

**Comment by lscheffler** [comment]
With your approach from above I see some problems
- PE should only open files that belong to the PE instance, not any file.
- I use a multitude of VFP environments, this is each is a single directory structure with a FOXUSER / Registry setting. Some *might* use PE, others don't. The plugin is **global** to GF, so it could not deal with this.
- the plugin needs something to open files *even if no PE is active*. We know nothing about the way the user ticks - we can only see what you and I do. What is different enough.   
- Plugins are so static. 
- And odd to maintain.
  - PE knows nothing if and where GF is installed
  - we do not know the order both applications are installed
  - we need to talk the user into placing the plugin
  - we would need a naming convention - this is next to magical numbers and hard coded passwords. Look how terrible it is to find a certain prg in Thor's proc directory. It's impossible to use dynamic search, and hell to see a certain file. All is *Thor_Proc_BlaBla*, nothing the eye could fix on. Nobody knows when to search Thor_Proc* or Thor_Tool* or whatever.

My idea was, PE binds to the whatever-opens-file-method of GF (call delegate code before event code). And if PE opens a certain file, PE sets a property of GF. If this property is set, the open file method of GF just does nothing. (side note: if more then one PE instance is active, they must check this property. If set, they must ignore the call.)   
Logically the interface structure of GF must be defined / known to PE.

And if we have this, it's simple for PE to hook to *GF Replace*.

**Comment by lscheffler** [comment]
My ideas how this should work, creating the bindings.
### Scenario 1
1. PE running
2. GF starts
3. GF scans for PE instances and notifies the PE instances about itself starting, handing the object
  - PE needs a method to receive this.
  - This methods cares about the eventbinding to whatever PE likes to watch (definition of this interface is a different problem. Control who opens a file for edit, see below)
4. If GF is closing down, it checks for AEVENTS, release the bindings 
5. If PE is closing, it checks for AEVENTS, release the bindings 

### Scenario 2
1. GF running
2. PE starts
3. PE scans for GF, creates the bindings as above
4. Closing GF/PE, as above

---
My idea how to edit a file from GF.
### File edit
1. GF sets a property like `GF.IsOpen = .F.`
2. GF calls a method EditFile(cFile...)
3. PE receives the call (before GF.EditFile(cFile...) runs )
4. PE checks, `!GF.IsOpen AND cFile Inlist PE.FileList` (&&!GF.IsOpen to figure out if a different PE already opened the file)
5. if Yes
  -  `GF.IsOpen = .T.`
  - Edit File
  - Return
6. if No
  - Return 
7. GF.EditFile(..) runs after return, if `!GF.IsOpen` GF opens the file for edit

So  3 .. 6 happen only if PE is running, fully transparent to GF. All GF cares about is the property.

---    
And PE must not open files that do not belong to this instance of PE. It simply should not deal with any file possibly found by GF. GF could run for a totally unrelated folder. (Like someone looks up code somewhere else).    
Also I would like the *right instance* of PE to open the file - and take care of following git related actions. There could be two PE open, that care about different repository. The code above calls for the first possible instance of PE. How do you know that a file not belonging to PE should be transformed / gitted at all, even know if this file is in a repo? Also without git active for a given project, there is no need to hook in at all. (A PE not using git must not bind - but this is the problem of this PE instance)

And, in my mind, each instance of PE should care about itself, the plugin should not scan the PE instances for a file.

----
So the main work is the code looking up the *other* application. For the user this is fully transparent.   
Using binding, it's relative simple to let the user control this - an option on PE will simply not bind, while an option on GF must be checked by PE in Scenario 2

**Comment by DougHennig** [comment]
Why so complicated?

My suggestion requires adding 4 lines of code to one method in one project (GF). Your suggestion requires a lot more code in several methods of 2 projects. More code = more points of failure and more testing. What benefit is there for the extra complexity?

As for PE not editing a file it doesn't know about, it already returns .F. if the file isn't in the project. So, the code in GF is actually:

```
llHandled = type('_screen.oProjectExplorers') = 'O' and ;
    _screen.oProjectExplorers.Count > 0 and ;
    _screen.oProjectExplorers[1].EditFile(lcFileName, lnLineNo, justfname(lcFileName), lcMethod)
if not llHandled
* use existing code to edit file
endif
````

Yes, this assumes the first instance of PE. However, although there is support for it, I highly doubt anyone has more than one instance open at a time. And even if it's the second instance of PE that has the file, no harm done since llHandled will be .F. and the existing code will edit the file.

**Comment by lscheffler** [comment]
Just get me right. We are on a discussion. Nothing will happen soon, I still wait for Jim to fix the Thor related stuff, and then I need to run tests.    
If you really like this implemented as you post, there is no problem. I just point the problems I see with this approach. For me it's only brute force, where there are more elegant ways. Nothing important. 

---
> Why so complicated?

- From GF's POV a search on startup and a comparison of a property is more simple then the query on every edit. 
- The wish to open files on PE is PE sided, so the complications should be there. For GF there is no use on this.
- Because problems of PE should be handled in PE
- If you allow multiple instances of PE, the code must handle multiple instances of PE. Else something is very wrong.
- Think PE is added as scope of GF search. (Not a bad idea) And the second instance is picked. Then it starts to edit or not on the first one. I can see the issue, so I solve it in front of it. Sure I can add code dealing with this in GF - but very soon it's more complicated then eventbinding.
- Since you like to trace changes on edit, I'm still think about *GF Replace* as next step to trace. Here there is even no choice. It's just trace. Eventbinding solves it elegant. Or the next piece of such code, or two, if you decide to store the before and the after replace state to git.

**Comment by DougHennig** [comment]
- A check for the existence of PE has to be done every time because it could have been closed or opened since the last check.
- It isn't PE that's driving this; it's the user telling GF they want to edit something. So it isn't "PE sided"; it's simply GF telling PE to edit the file rather than doing it itself.
- Agreed that any problems should be handled in PE.
- The easiest way to handle multiple instances of PE is to call EditFile in each instance until .T. is returned.

**Comment by lscheffler** [comment]
> * A check for the existence of PE has to be done every time because it could have been closed or opened since the last check.

For that, each instance (GF and each PE) only need to check if the *other* app is running and call the PE eventbinder. In case (I'm not sure here) they must release their bindings on Destroy. That's the trick. ***All** care to create the binding*
>     * It isn't PE that's driving this; it's the user telling GF they want to edit something. So it isn't "PE sided"; it's simply GF telling PE to edit the file rather than doing it itself.

I'm on an app sided view on this. What is the sense using PE's edit at all? [cite, from OM] *it can automatically call FoxBin2PRG or other program to generate the text file when you close the editor* [/cite]. So this means PE likes to take care about the files it contains. Whatever the user wishes, it depends on PE running - and PE able to do the job.
>     * The easiest way to handle multiple instances of PE is to call EditFile in each instance until .T. is returned.

And that's exactly what I like to avoid in GF. Code over code that deals with PE. For now your approach means
each call for edit on GF must figure out if PE exists, like 
```` 
llHandled = .f.
IF type('_screen.oProjectExplorers') = 'O' and  !ISNULL(_screen.oProjectExplorers) and;
    PEMSTATUS(_screen.oProjectExplorers,'count',5)
  FOR lnProject = 1 to _screen.oProjectExplorers.Count
    llHandled = type('_screen.oProjectExplorers[lnProject]') = 'O' and  !ISNULL(_screen.oProjectExplorers[lnProject]) and;
       PEMSTATUS(_screen.oProjectExplorers[lnProject],'EditFile',5) and ;
       _screen.oProjectExplorers[lnProject].EditFile(lcFileName, lnLineNo, justfname(lcFileName), lcMethod)
    IF llHandled THEN
      EXIT
...
    IF !llHandled THEN
     GF.EditFile()
...
```` 

You can not tell me that this is less complex then Eventbinding. My approach just needs one simpler loop one time at startup of GF - and a much simpler test on start of PE. For simplicity I would not bind to PE.EditFile directly, but to a wrapper, so one does not need to look up AEVENTS(). This wrapper is checking the files collection and dealing with the GF property. PE.EditFile I would not touch, so it remains stable.

The real good is, no running code needs to be touched, except a call on startup, and possibly on destroy (I'm not sure of the object reference in BindEvent auto releases)
- PE offers a method to start the binding
- PE creates a wrapper for PE.EditFile to bind to and to handle the special problems
- PE needs to search for GF instance on startup
- GF creates something to scan for PE instances on start
- GF creates a wrapper for GF.EditFile, dealing with the property (test and reset) and calling GF.EditFile in case.

The binding is between two methods (iow events) that in no way alter existing code.
```
*The whole wrapper GF sided:
LPARA toThis, ...
*GF.FileIgnored is .T., except altered by PE.
*This point will be reached after all eventbinding is run.
IF GF.FileIgnored
 GF Editfile(...)
ELSE  &&GF.FileIgnored
*just reset the flag
 GF.FileIgnored = .T.
ENDIF &&GF.FileIgnored
```
```
*The whole wrapper, PE sided:
LPARA toGF, ...
IF toGF.FileIgnored AND file_in_collection
 PE Editfile(..)
*We have done it! Notify successors.
 toGF.FileIgnored = .F.
ENDIF &&!toGF.FileIgnored AND file_in_collection
```
This is so much cleaner - and faster. The problems are on startup, once per instance. For GF, it's the same code, for PE a bit more, and the target for eventbinding. I would do this PE sided. Sure, one can do GF sided, but a PE without FoxBin2Prg/git could simply ignore the binding for itself.

**Comment by Jimrnelson** [comment]
I disagree very strongly with the "binding" approach Lutz has outlined.  

PE should be able to offer a "service" that any program can take advantage of.  It should be transparent to PE what the program is or how it acts.

For this discussion, you have been discussing GF as if it was the only such program that might be interested in using this "service".  

It isn't.

PEMEditor should be able to use this "service" as well, along with IntellisenseX and a few Thor tools.  All of these should be able to do so without requiring any modification to PE.  (It would be a ugly implementation indeed if every time a new program wanted to use this "service", PE would have to be modified.)

As a matter of fact, IntellisenseX and the Thor tools are not APPs, they are simply PRGs, so binding is not even possible.

***

Doug, I suggest one modification to `_screen.oProjectExplorers`, and that would be a method to loop through all the items in its collection.  That would make the code to invoke this just a few lines long.

```
if type('_screen.oProjectExplorers.count') = 'N'
    _screen.oProjectExplorer.SomeNewMethod(lcFileName, lnLineNo, justfname(lcFileName), lcMethod)
else
* edit the file
endif
```

(and I would remove the redundant parameters for lcFileName ... the third parameter can be obtained from the first)

Once that is ready, it should be referenced in PEMEditor, IntellisenseX, and those few Thor Tools.  It would also be handy if it took care of the MRU list.

**Comment by lscheffler** [comment]
> As a matter of fact, IntellisenseX and the Thor tools are not APPs, they are simply PRGs, so binding is not even possible.

For simplicity, an *app* is something running we do not care if it is filetype app, prg, or anything else. No need to mince words.

*In general, this issue is not a problem of GF or any other app. It's PE that need to keep it's integrity. **So it's the number one best idea PE takes care of it** The apps might be happy to support - nobody likes a timer on PE checking for a new app running - but support only.* 

> I disagree very strongly with the "binding" approach Lutz has outlined.
> 
> PE should be able to offer a "service" that any program can take advantage of. It should be transparent to PE what the program is or how it acts.

See above, it's a service **toward** PE. The other apps do not care about the problems.
 
> For this discussion, you have been discussing GF as if it was the only such program that might be interested in using this "service".
> 
> It isn't.
 
> PEMEditor should be able to use this "service" as well, along with IntellisenseX and a few Thor tools. All of these should be able to do so without requiring any modification to PE. (It would be a ugly implementation indeed if every time a new program wanted to use this "service", PE would have to be modified.)

no doubt

From my POV, PE likes to keep it's stuff actual - iow the state of the *.??2 files and the repository should represent the state of the binary sources.  None of apps mentioned or one might think of cares about this.
1. It's not about *Edit*
2. It's about tracing save / close of files
3. This is done by PE through project hooks functionality
4. As I understand it, this is a straight-through-the-wall approach.
  - Aside I dislike this VSS like action-by-file-change thinking, but this is my taste. I **must** be possible to disabled on PE side (I think there is a way to disable git etc.) - and then PE should not hook in at all. And then it *must not be called at all*. Calling PE for nothing is a useless waste of time and useless complication
5. It's not the problem of any app if PE likes to trace this
6. There is no need to run this through `PE.EditFile`. It's very simple to just notify PE that a certain file is open for edit / change / whatever PE Eventbinds to the filesystem and works on this.
7. In general I dislike the idea that PE opens file for a different app
8. It's right, PE must offer an interface, the apps can hook in, in the one or the other way
9. Since it's a problem of PE, any change of the apps **must** be minimal
10. For my approach, the whole *Change* for PE for a new app is simply that it must figure out that a certain app is running. The bindung to ***any** app* runs trough the same code as my last example in https://github.com/VFPX/GoFish/issues/154#issuecomment-1872565008 - as long as the app offers the method to bind to. This is transparent to PE.
11. If a special app is not based on objects, it still might call the wrapper method of PE - it only must provide the property. Simple enough. To PE this is transparent too. But then this app must struggle with the ugliness of iterating PE instances on every call.
12. Eventbinding is reliable. I have the feeling that this is about mistrust about the *magic* way this acts. It's as simple, but without the everytime-bloat on the caller side.

> Doug, I suggest one modification to `_screen.oProjectExplorers`, and that would be a method to loop through all the items in its collection. That would make the code to invoke this just a few lines long.
> 
> ```
> if type('_screen.oProjectExplorers.count') = 'N'
>     _screen.oProjectExplorer.SomeNewMethod(lcFileName, lnLineNo, justfname(lcFileName), lcMethod)
> else
> * edit the file
> endif
> ```
> 
> (and I would remove the redundant parameters for lcFileName ... the third parameter can be obtained from the first)
> 
> Once that is ready, it should be referenced in PEMEditor, IntellisenseX, and those few Thor Tools. It would also be handy if it took care of the MRU list.

- It's still needs to check for PE on every call of any app - for nothing. It's so awkward and useless code for 90% of the users - that do not use PE at all, or do not care about FoxBin2Prg / git or dislike the per-file-change approach. 
- The EventBinding is minimal disturbance, it's only a hickup on startup and a tiny change to the EditFile
- Without Eventbinding, each app must be maintained to keep up with PE.

**Comment by DougHennig** [comment]
@lscheffler, you are only thinking about generating text file from binaries. But PE's EditFile function does a lot more than that:

- The minimum behavior is to refresh the TreeView in PE so you see the "modified" icon if the file was changed and it's under source control. Right now, if I have PE open and use GF to edit a file, after the editor is closed, PE doesn't refresh so the icon incorrectly shows that the file is unchanged.
- EditFile supports both before and after edit events, so a developer can create a plugin that, for example, automatically emails all team members whenever certain files are edited, such as common framework files.
- It could also do automatic backing up before editing if the person isn't using Git.
- They can even have no functionality at all: the call to FoxBin2PRG is optional in PE, so in your case, you simply wouldn't turn that on.

It's up to the developer to decide what tasks they want performed when a file is edited.

So, as @Jimrnelson suggests, advanced editing of a file is a service that PE provides. Any code can take advantage of this advanced editing through a single method call. It's similar to the idea of the EDITSOURCE function in VFP: it's a service VFP provides rather than having to manually invoke the appropriate editor for the type of object being edited. In this case, it's an advanced, customizable version of EDITSOURCE. There is no way you would want to do the work to add that type of functionality to GF, PEM Editor, IntelliSenseX, etc. Instead, call the service if it exists.

Addressing some of your comments:

> Calling PE for nothing is a useless waste of time and useless complication

It's one method call, similar to calling EDITSOURCE:

```
if PE exists
    oPE.EditFile
else
    EditSource
endif

I don't see how that is complicated. And the code runs is a fraction of a second so how is it a waste of time?

> Since it's a problem of PE, any change of the apps must be minimal

I believe adding 4 lines of code could be described as "minimal".

> For my approach, the whole Change for PE for a new app is simply that it must figure out that a certain app is running.

So PE would need code to check for GF, PEM Editor, IntelliSenseX, and every other app any developer might write? That means any time someone wants to use a service of PE programmatically, they have to let me know so I can add yet another app check at startup. How does that make sense?

> It's still needs to check for PE on every call of any app - for nothing. It's so awkward and useless code for 90% of the users - that do not use PE at all, or do not care about FoxBin2Prg / git or dislike the per-file-change approach.

How is one line of fast code (the IF TYPE statement) awkward and useless? We as VFP developers use the TYPE command all the time. If someone isn't using PE or doesn't need the advanced features of the service, the performance hit of the TYPE command, which is milliseconds, is completely unnoticeable. And I can guarantee that even if someone doesn't want it to call FoxBin2PRG, if they are using source control, they want to see the "modified" icon in PE.

I appreciate your thinking of alternatives. It's always good to explore other ideas. I use event binding a lot; in fact, that's how PE is notified when the editor is closed. However, in this case I don't think it's appropriate. You haven't convinced me that it has any benefits in this case and that it requires a significant amount of coding in both PE and every app that wants to use it as opposed to minimal change in those apps and just the one change Jim suggested in PE.

So let's just go with my suggestion of using EditFile as a service, OK? If you'd rather not make that change, I can do it.

**Comment by lscheffler** [comment]
@DougHennig    
It starts with the *modified* icon, or the like, I see no use in it. It's so VSS thinking.  But this is a matter of taste, as most on git.   
I simply do not think any tool should be changed for the convenience of PE or it's interface. From GF POV, I see no use at all in this.

As you and Jim pointed out, there might be *many* apps. It's a really bad idea to change all of those apps to integrate a third party tool like PE. For me, it's best PE cares about this itself - requesting an interface to eventbind and a return value - only that it is a bit odd to figure out that a certain tool is starting. That's why I offered to hook to PE on startup of GF, and leave anything else to PE.

The idea to use the PE edit method is only a kludge to solve PE problems. As longer I think about it, the more I reject the issue.

*I recommend binding PE to the file system.* Solves all in one try, even if a file is read outside VFP or in a different instance of VFP. And no fuzz and extra code to maintain in any tool that perfectly cares about itself. We have a lot of stuff not maintaned in VFPX, so I do not recommend to create new dependencies.

**Comment by DougHennig** [comment]
I spent some time testing binding to the file system. However, it does not work reliably in VFP. You can see this yourself if you run the VFP sample Solution.app and try the event binding example. Choose the file system event, enable it, choose No so it gets notification of all events, then edit and save a PRG or a class in a VCX. Some of the Windows events appear but not all. For example, sometimes you will see a TMP file created, the PRG deleted, then the TMP file renamed to the PRG, but sometimes you only see the TMP file created. When you edit a class in a VCX, usually you only see the attributes of the folder the VCX is in changed. So, while this seemed like a good idea, I cannot get it to work reliably.
