### ISSUE TITLE
File Too Large

### ISSUE THREAD

**Issue by dcipher** [VFPX/GoFish#158]
## ℹ Computer information

- VFP version: VFP
- GoFish version: 6.2.007
- Last GoFish version w/o bug (if available):

## 📝 Provide detailed reproduction steps (if any)
I am searching in a vcx file.

1. Search for "MP
2.Click goFish
3. After several minutes a dialog box is displayed with the message that the file is too large.

### ✔️ Expected result
Expected to see a list of code item containing "MP. When I use the VFP Code Reference tool it works fine and shows me 5111 matches.

### ❌ Actual result

Dialog box saying that the file is to large.

## 📷 Screenshots

_Are there any useful screenshots? WinKey+Shift+S and then just paste them directly into the form_

**Comment by lscheffler** [comment]
Yes, there is an issue with to wide searches. The memo file is to large. Limit your scope. See #49

Each hit stores the prg and the procedure. to the memo file. Imagine how this is bloating on unlucky search strings. CR does not store this stuff, it only stores the very line, so there is not much danger.

I'm still not sure how to solve this, but it I'm working on it.

Closed, because this is a duplicate.
