### ISSUE TITLE
Time stamp expressions should respect SET DATE settings

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#189]
📝 Provide a description of the new feature

There's a date format as DD.MM.YYYY and 24 for hours in many countries in Europe  - 01/02/2024 is 02.01.2024 and 01:00:00 PM is 13:00:00 (PM). This is **SET DATE GERMAN** settings.

Your format is unusual for us, the same as ours is unusual for you :-) GoFish should respect SET DATE settings.

![2](https://github.com/VFPX/GoFish/assets/142881527/bd868a3b-1136-40df-9e7c-56ca686bd428)

![3](https://github.com/VFPX/GoFish/assets/142881527/ccf305f5-0ea8-493e-8218-14532eee5fe8)

**Comment by Jimrnelson** [comment]
@klepetox

I find this to be most curious as there is no SET DATE reference in GoFish, so what you are seeing is what VFP uses as the default in a new data session.  I would have expected that to be GERMAN in your case.

This will be corrected in the next release.

**Comment by Jimrnelson** [comment]
@klepetox @DougHennig 

One more thing has been bugging me about that crowded "Advanced" form and I'd appreciate your opinion.

Originally, almost all search options were found only in the advanced from (only the search phrase and scope were on the main form).  

Over time, many of the search options were duplicated onto the main form and I find that duplication undesirable. 

I have been considering removing all of the duplicated items from the Advanced form so that form would contain only less used options that are not found on the main form.

This would make it more obvious what the "Advanced" options are.  Then again, it might also cause some first time confusion.

What do you think?

**Comment by DougHennig** [comment]
Agreed.

**Comment by Jimrnelson** [comment]
@DougHennig 

I understand that to mean you agree with my suggestion.

**Comment by klepetox** [comment]
I use Advanced search form only sometimes, most of the important settings is on the main form. I agree, the form "Advanced search" could be more simple.

**Comment by klepetox** [comment]
You are right. I have a procedure "InitDataSession" and SET DATE GERMAN must be in it, because the default is AMERICAN.

cDateSetting=SET('date')

new datasession init:

SET DATE &cDateSetting

**Comment by Jimrnelson** [comment]
OK, at least that makes sense now.

**Comment by klepetox** [comment]
Please, if you will do these corrections, try to include SET POINT setting too. This is as important as SET DATE setting. In the meantime I have no problem with it, but without this setting expression 9.99 will be 9.00 if SET POINT is to "," (comma).

**Comment by Jimrnelson** [comment]
Easy enough to do.

Where does this have any effect?

**Comment by klepetox** [comment]
I do not know where. GoFish is too advanced and complex, maybe somewhere or nowhere, but maybe it could be another problem in the future. I have permanent problem with SET POINT. Set it to point and return it back, when I read settings from memo fields - save old point, set it to point, read expression and restore point back. But ignore it. So far there has been no problem, let it not be too complicated, I prefer to leave it alone. I withdraw this request (SET POINT).

**Comment by Jimrnelson** [comment]
I've learned that there's a curious problem with changing the setting for SET DATE in that in a couple of internal GF tables, the value stored is of type C(24) rather than Timestamp.

I will have to see how to correct this before releasing this update.

So I can test properly, can you please attach your file    `Home(7) + "GoFish_\gf_search_history.dbf"` ?

**Comment by klepetox** [comment]
File attached. It was empty, (I do not save history in options) so I did some fast searching.
[gf_search_history.dbf.zip](https://github.com/VFPX/GoFish/files/14668497/gf_search_history.dbf.zip)

**Comment by Jimrnelson** [comment]
For my own use, I am ever so close to not saving history.  Occasionally I will go back to searches from earlier today.

For purposes of maintaining GF, though, I keep a few days history around.

**Comment by Jimrnelson** [comment]
If I try

    SET DATE GERMAN

then the date comes out as requested, but not the time.  Is there some other setting to control that?

![image](https://github.com/VFPX/GoFish/assets/81179335/40ec8335-6d5f-4053-9dc6-652e2c3546d2)

**Comment by klepetox** [comment]
It will be probably SET HOURS TO 24 instead of 12. I have tried it now and it seems to work.

**Comment by Jimrnelson** [comment]
Implemented in Version 7.0.18 - 2024-03-24
