### ISSUE TITLE
GoFish5 Thor tool altered incorrectly

### ISSUE THREAD

**Issue by rschummer** [VFPX/GoFish#23]
## 📝 Provide detailed reproduction steps (if any)

Installed v5.1.000

### ✔️ Expected result

GoFish to start without a problem

### ❌ Actual result

Installation process either installed or edited the Thor_Tool_GoFish5.PRG and added "EndProc" at the end of the line that executes GoFish

Do 'J:\WLCPROJECT\VFPX\THOR\THOR\TOOLS\APPS\GOFISH5\GOFISH5.APP'**EndProc**

Not a big deal as I corrected it and when it popped the source code open when running GoFish.

**Comment by lscheffler** [comment]
So like a missing CRLF or an additional `EndProc`?

I even have no idea what plays with Thor here .... Every project deals an other way with Thor. This is such a madness.

**Comment by lscheffler** [comment]
Closer. The problem is in  GoFish.prg. There seems to be some odd setting to my comp, or I do not grok it.

In GoFish.prg, Procedure RegisterAppWithThor there is
```

		TEXT To lcCode Noshow Textmerge
  		Do '<<lcFullAppName>>'
		ENDTEXT

		TEXT To lcPlugIn Noshow

EndProc


Define Class clsGoFishFormatGrid As Custom
...
		ENDTEXT
		.Code = Strtran(lcCode + Evl(lcPlugIn, ''), '***TEXT***', 'Text')

```
This concentates lcCode and lcPlugIn. And I end up with `...GOFISH5.APP'EndProc`
Thi is the following code will, do the same. 
```
lcFullAppName = 'mumu'
		TEXT To lcCode Noshow Textmerge
  		Do '<<lcFullAppName>>'
		ENDTEXT

		TEXT To lcPlugIn Noshow

EndProc
endtext
?lcCode+lcPlugIn

```
Is there any other result on your comp? I know there is some oddness with empty lines I need to look up, but the code is old and I don't see the difference.

**Comment by lscheffler** [comment]
update worked so far. Code looks ok. @rschummer can you run a test?

**Comment by rschummer** [comment]
I updated to 5.1.001 and everything worked fine running GoFish. Closing the issue.
