### ISSUE TITLE
Folders excluded from searching (files to skip) are ignored when I search in "All Open Projects"

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#244]
Folders excluded from searching (files to skip) are ignored when I search in "All Open Projects".
If I search in project in current dir, those folders are excluded correctly.

## 📷 Screenshots
![1](https://github.com/VFPX/GoFish/assets/142881527/c9692629-0c60-4ee6-91ab-bf8fc3bcf95d)

**Comment by Jimrnelson** [comment]
Fixed in Version 7.1.05 - 2024-06-08

File names (with paths) inside GF can be all lower case, all upper case, or mixed case, depending on how the list if obtained.

I thought I had taken care of handling all the combinations but missed this one - I had to add UPPER( ) to one line of code.

Hoping that there aren't any others lurking.

**Comment by klepetox** [comment]
Works well, thanks for the quick fix.

**Comment by Jimrnelson** [comment]
You're welcome!

Always good to hear from you.  Your error reports are very thorough.

I can't believe you are the only one seeing these issues, so my guess is that you're the only one reporting them.

Thanks!
