### ISSUE TITLE
Editing "Options UDF" program can cause foxpro to crash

### ISSUE THREAD

**Issue by klepetox** [VFPX/GoFish#275]
## 📝 Provide detailed reproduction steps (if any)

1. Run GoFish options form.
2. Select New in V7 - Options UDF - Edit UDF.
3. Now the UDF .prg is open for editing.
4. Click anywhere outside of the program window.
5. Program window is dismissed and GoFish and the whole Foxpro is dead.

✔️ Expected result
Program window should stay open with possibility to return in it.

Maybe should be `Modify Command (lcFile) Save` instead of `Modify Command (lcFile)`. `EditSource()` is another possibility.

![1](https://github.com/user-attachments/assets/c3b2cce1-6789-49d4-8715-f546dfbdb8b4)

**Comment by Jimrnelson** [comment]
@klepetox 

This has been addressed in today's update, Version 7.1.18 - 2024-07-26.

I say "addressed", rather than "fixed", because there is some unusual behavior when running 'Modify Command' from within a modal form.  My hope is that my change for this is satisfactory; that is, at least it doesn't blow VFP out of the water any more.

**Comment by klepetox** [comment]
Hi Jim, I confirm that the modification is sufficient and has solved the problem Thank you.
