### ISSUE TITLE
GoFish through Thor is getting an error

### ISSUE THREAD

**Issue by CHamlinPNP** [VFPX/GoFish#3]
## 📝 Provide detailed reproduction steps (if any)

1. … Select GoFish through the Thor menu
2. … set the string to look for and the project to search
3. … does the search and then gives an error

### ✔️ Expected result

Expect it to display the results

### ❌ Actual result

Rather than the results...it gives an error. The issue is that ProcCode field is a memo and you cannot order by a memo field.

## 📷 Screenshots

The follow screen shots will show the issue I am having...
![Screenshot 2022-07-01 135301](https://user-images.githubusercontent.com/34104227/176947348-1275f57b-c04a-4ed9-b76f-b455c344ff5e.png)

![Screenshot 2022-07-01 135557](https://user-images.githubusercontent.com/34104227/176947372-f48131fe-592e-47a0-a4d9-72d1493db613.png)

[Structure.txt](https://github.com/VFPX/GoFish/files/9030844/Structure.txt)

**Comment by CHamlinPNP** [comment]
It has been nearly 3 weeks...has anyone got any suggestions for me to try?

**Comment by CHamlinPNP** [comment]
After over a month and not hearing anything... I at this point in time can only assume that the GoFish project is defunct and unsupported.

**Comment by PatrickvonDeetzen** [comment]
Hi,
i had this error too, but it is not related to Thor.

When i accidently clicked the column header of a memo-field showing the results runs into an error. The following memo-columns will throw the error.
- Proccode
- Statement
- Code

There is a short trick around it that i used to get it back to work:
1. Start GoFish (don´t start the search!) 
2. Click some column header (like "Name", "File Name" or "Method/Property Name")
3. If you follow step 1 & 2 these will crash two times. Just start GoFish again. The third time GoFish will work again. This works because GoFish saves up 3 of your last search columns. 

As for a more permanent solution i added a fix for this problem in my recent Pull-Request so this won´t bother anyone anymore. 
;-)
