### ISSUE TITLE
Bottom page highlighted doesn't respect Whole word checkbox

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#4]
## 📝 Provide detailed reproduction steps (if any)

1. Specify a search string of "item" (which the quotes) and the Toolbox project. 
2. Check Whole word
3. Run the search

### ✔️ Expected result

In the bottom pane showing results in context, only "item" as a whole word should be highlighted in green.

### ❌ Actual result

All occurrences of item are highlighted in green.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/30271640/180862748-02fca64b-25de-43c0-82e1-5c5d4f9f0935.png)

**Comment by PatrickvonDeetzen** [comment]
Just added a fix for this problem in my Pull-Request.

The problem was, that the highlighting for the search got applied in two different places using different functions. 
- Once with "RegEx"(ok)
- Once with "Strtran" (wrong)

**With active option "Whole word"**
![2022-08-14_11h39_33](https://user-images.githubusercontent.com/74181432/184531246-c25791b2-2338-45cb-a94a-7e7eae35f513.png)

**With inactive option "Whole word"**
![2022-08-14_11h40_27](https://user-images.githubusercontent.com/74181432/184531250-3ebc7b5d-11fd-48aa-995e-a8e857acd8df.png)
