### ISSUE TITLE
GoFish 6 - Not Running After Installation

### ISSUE THREAD

**Issue by ugurlu2001** [VFPX/GoFish#53]
## ℹ Computer information

- VFP version: VFP version: 09.00.0000.7423
- GoFish version: 6.1
- Last GoFish version w/o bug (if available): 5.1.009

## 📝 Provide detailed reproduction steps (if any)

1. I installed GoFish latest version via Thor Update,
2. After installation, start the GoFish6
3. GoFish started via some questions Similar like this ' C:\Users\ugur\AppData\Roaming\Microsoft\Visual FoxPro 9\GoFish_\GF_Saved_Search_Results...' file is already exist, Overrite it ( I confirmed more than hundred time YES overrite).
4. Continue "ask some questions (more than hundred)
5. I kill VFP process via Task manager 
6. I restart VFP and run Gofish : Error message is: 
7. Program Error " Unhandled Structured Exception.
				ErrorNo: 1
				Message: File 'D:\MyDevFolder\MyAppFolder\gf_search_history.dbf' does not exist.
				UserValue:
				Details: D:\MyDevFolder\MyAppFolder\gf_search_history.dbf
				Procedure: usetable
				LineNo: 12 "
8. GoFish App is on my vfp installation folder "C:\VFP9"; error, is firing on my application path : " 'D:\MyDevFolder\MyAppFolder\"
And Home(7) path is "c:\users\ugur\appdata\roaming\microsoft\visual foxpro 9\"
9. I replace the previous version of GoFish now and working well. ( Lost of my previous search history )

Is there a way to use latest version of GoFish? Is there an easy way re-start update process?

**Comment by lscheffler** [comment]
Sadly the upgrade to Version 6.0 failed - and I have no glue why. It looks as something was running twice.   
Even more sadly I fear your old stuff might be lost.   
It is not clear why you had this *file exists* problem.
The second problem is simple due to the problem that the update failed and files / databases expected are missing.

## If you really need your old stuff
-zip `Home(7)+"\GoFish_"` and attach to a message here, I can try if I can fix it
## To make GF 6.0 running
- Go into Home(7)
- Delete all GF*.*
- Delete GoFish_ folder
- Delete GF_ReplaceBackups folder
- Delete GF_Saved_Search_Results folder
- if there is anything else that looks like GoFish, like named GoFish or GF, remove

Now there should be a clean system and GoFish 6.0 should start from scratch

**Comment by lscheffler** [comment]
See #63 for further discussion.
