### ISSUE TITLE
Problem opening SPR files

### ISSUE THREAD

**Issue by nmpetkov** [VFPX/GoFish#72]
## ℹ Computer information

- VFP version: VFP 9 SP2
- GoFish version: #.#.# 6.0.008
- Last GoFish version w/o bug (if available): no

## 📝 Provide detailed reproduction steps (if any)

GoFish searches and finds in SPR files, but when the corresponding line in the result table is clicked, this program file does not open in the VFP interface, but it is offered to open with application of the operating system.
The problem also occurs in GoFish version 5.1.

**Comment by Jimrnelson** [comment]
SPR file?   Never heard of it.  What is it?  How would one open it in FoxPro?Sent from my iPhoneOn Mar 20, 2023, at 9:43 AM, N. Petkov ***@***.***> wrote:﻿
ℹ Computer information

VFP version: VFP 9 SP2
GoFish version: #.#.# 6.0.008
Last GoFish version w/o bug (if available): no

📝 Provide detailed reproduction steps (if any)
GoFish searches and finds in SPR files, but when the corresponding line in the result table is clicked, this program file does not open in the VFP interface, but it is offered to open with application of the operating system.
The problem also occurs in GoFish version 5.1.

**Comment by lscheffler** [comment]
@Jimrnelson  From Help, File Extensions and File Types, .spr:   
*Generated screen program (earlier versions of FoxPro only)*

@nmpetkov We see no way to modify this type of file. How do you use this? GoFish handles this as any file VFP can not deal with - escalate to system.

**Comment by Jimrnelson** [comment]
@lscheffler 

Yes, I had seen that in the help file .  Not very illuminating.

**Comment by lscheffler** [comment]
So you say you run screens inherited from FoxPro? OMIPU. Well, it's your taste. So how do you open these files?
Modify Command? Would you mind the publish an example of the scx source? Former company reworked this stuff ages ago so I have no idea.   
Any other outdated file types?

**Comment by nmpetkov** [comment]
All commands valid for prg and mpr files, are valid for spr files.
:-)
Yes, I also converted old Foxpro 2 files many-many years ago, but some files stay not renamed to prg.
If with GoFish you search an old project, you will have problem like me to open spr files.
It is just change to 1 line of code. I think it is good for GoFish to support all file types, which VFP supports.

**Comment by nmpetkov** [comment]
> Would you mind the publish an example of the scx source?

You don't need an example scx file. Just change one of your prg files to spr extension and apply VFP commands.

**Comment by nmpetkov** [comment]
> Any other outdated file types?

I don't think there are any others.

**Comment by lscheffler** [comment]
> It is just change to 1 line of code. I think it is good for GoFish to support all file types, which VFP supports.

For this problem, yes. What it does not:
- not in file type list in advanced
- will show / store the whole file as snippet, not just procedure/function as for prg 
- will not show class / procedure etc. in search
If I drop such a file into a pjx it will end up as "other file" - and will be modified via MODIFY FILE

Would you like it to open as file or program?   

**I** would just rename all the \*.spr to \*.prg and call it even.

**Comment by lscheffler** [comment]
No Problem. I just dropped the file into the PJX and looked for the default. *Add* might accept many, if not defined otherwise.    
But since you say it could be compiled, just as PRG will do.

----
Off topic   
Foxref does dangerously different then the PJX. A header file should not be modified with EDITSOURCE. Imagine a prg namend *abc.prg* including a header *abc.h*. If you EDITSOURCE("abc.h"), alter and close, it will compile the **header** to *abc.frx*. This might end up in a lot of fun for *Do abc*.   
The code even suggest *LOG* or *TXT* - give it a try.   
BTW, what is *\*.ME*?

**Comment by nmpetkov** [comment]
> BTW, what is _*.ME_?

I do not know. There is MEM file in VFP directory, buit it is other.

> FoxRef has other problems

This is why GoFish needs to be improved. Foxref opens the files with the search selected, and that's fine to borrow.

About what needs to change for GoFish to start opening all code files: 

![image](https://user-images.githubusercontent.com/628801/226583711-df3bfb6c-b789-4f01-9500-83f0d4bd3a64.png)

**Comment by nmpetkov** [comment]
Actually, in the above program code, using $ is not save, INLIST should be used.

**Comment by lscheffler** [comment]
I discourage to do something in files generated like MPR, this should be done on MNX level. There is value if one fiddles with GenMenu.app (as I do) but else, no.   
I agree that view this like a PRG, but to alter it might unsync the build process. So I would rather go for `MODIFY COMMAND  (lcFileName) NOEDIT RANGE ...` here. At least for MPR QPR, since I do not know if you generate the SPR. If you generate this, I think it should be `NOEDIT` as well.   
Again, I do not see how you create this files (and if you do not create them, why not simply rename to standard prg. The MPR QPR are named that way to discourage the idea to change them.)   
GoFish wisely MODI FILE those, so they do not auto-compile on close. (I have no idea how long we have NOEDIT, but GoFish is older then FoxRef, for all I know.)

So it depends what you do with the spr. Again, MODI COMM without NOEDIT might not be a general problem here, since it's very exotic.

**Comment by nmpetkov** [comment]
There is generator programs comming with VFP, wich produce SPR, MPR and QPR files. Once included in the project, it is save to edit them. 
There may be a reason for the user to edit them, and it is the programmer who at his own risk can and should do so. I don't see why GoFish needs to put a NOEDIT clause.
SPR files occur when converting screens from an old version of Foxpro. They are normal code files, freely editable and VFP compiles them normally. Yes, users could be advised to rename them to prg files, but I don't see why they should oblige, since there might also be a renaming conflict (same spr and prg file names.

**Comment by lscheffler** [comment]
So, you say that a SPR is a file that in general would be generated, only you don't. I accept that this is your way, no problem. Only I must do for the general audience, so if MODI COMM, then NOEDIT. To dangerous. Or a lot of work with options for your special need.   
I'm here because **I** had a special need, that's why **I** have forked and work the project. All I can offer (for free) is MODI COMM NOEDIT, and even that I consider odd, since from my POV none of this files belong within the search at all.

If you need otherwise, this is an open project, just fork, fix it to your needs - and if you think there is a general use of your way, make it optional and ask for a merge. It's just VFP. See [contribution](https://github.com/VFPX/GoFish/blob/master/.github/CONTRIBUTING.md). Else it is possible to keep your private fork while merging the general changes, only you loose Thor update and gather some work.  
Pro tip: If you do this, make it complete and add the spr type to the *Advanced Search* from, it's missed there. Also, those file (types) should be handled like a prg, for searching for classes, methods and the like, and getting an own node in the tree, for example as "Generated" or per type.

**Comment by nmpetkov** [comment]
First of all I want to apologize for not understanding where I was - I thought this was where GoFish continued its existence with new releases. I know well how Github works, and since this is a fork mostly for your own needs, I won't bother you too much.

Regarding the thought expressed that you cannot get an idea how the SPR files are obtained. In a link I provide you with a sample project, which comes originally with the installation of Foxpro 2.6. You can open it in VFP 9, and it will prompt you to convert. Since you may not know where convert.app is, which is part of VFP, I am sending you inside convert.app as well. In VFP options there is a line "Converter", and you need to specify where the converter is located (it may be your default). After the conversion, browse the project - you will see SPR files in it.
https://esoft.cmstory.com/VFP%20sample%20project%20to%20convert%20from%202.6.zip

It's troubling to me how we can possibly waste each other's time by writing so much about such an obvious thing - the inclusion of an SPR extension to the editing capabilities. By the way, it doesn't matter where it will be included - both MODIFY COMMAND and MODIFY FILE work the same in this case. VFP applies all code options even to code opened with MODIFY FILE.

Before I finish writing on this matter, I ask you to answer why in the picture below, which is from GoFish Advanced options:

![image](https://user-images.githubusercontent.com/628801/226691891-dde0159d-9fc4-416f-8d31-1a0a84b9cc04.png)

The creators of GoFish knew enough about SPR files, and I think not being able to edit them is missing.

P.S.  It is written with the best feelings and wishes!

**Comment by Jimrnelson** [comment]
@nmpetkov 

> The creators of GoFish knew enough about SPR files, and I think not being able to edit them is missing.

Well, yes, Matt knew enough to include SPR files in his Advanced Search screen.  However, he borrowed the code from PEMEditor for opening files, which does not do anything with SPR files.

My suggestion would be to simply handle SPR files like MPRs (as you suggested earlier).  A one-line fix which has created a lot of banter.

Finally -- Matt's version of GF has been around since early 2011, it's kind of amazing for this issue not to come up until a dozen years later.

**Comment by lscheffler** [comment]
Sure, there are no bad feelings. I sound wrong often - even in German. Beg your pardon.

I must have missed the SPR in the Advanced Search, beg your pardon, again.

I guess it's all the time better to measure twice cut once, so if I don't understand a argue a bit.
There are - to me - major differences between MODI COMM and MODI FILE .
- The first highlights syntax, 
- uses Document View
- will compile after save/close.    

And that's the major problem - to me. Sorry if it is a bit longer. If you MODI COMM let's say a MPR that will be generated from an MNX in a project, VFP checks the timestamps to decide if the MPR needs to be generated (and compiled). Imagine what happens if the MPR is never then the MNX - it stucks with the code inserted. The same goes for my example with the header from above. You can look into your source as long as you like, your executable code don't fit the source, if it works at all, like the header example.
So that's why I reject to modify MPR QPR.

So if you say, your spr is generated **once** with converter, ok then it is the code. (Again, then it's a normal prg, I would rename, problem solved) If your converter created the MPR the same way - **once** then it is the same - and to me the same conclusion. 
Then, and only then all those files belong to MODI COMM - at least it will compile **and syntax check** on save.

I do not maintain Gofish as maintainer - except a bit of github service. This is because I was mostly working on GoFish the last months, so there was no need to bother Doug for each merge he just put through.   
The contrib link was mostly about the special conventions, not forking. 
I do bug fixes and minor changes, if I find the time, and making the SPR editable as not the big deal. Also setting MPR QPR as MODI COMM NOEDIT is not a big thing. I just need to learn what to do best.   
It's only if you need all of the three editable there are two ways
1. MODI FILE for MPR QPR to minimize the risk for general audience and SPR to MODI COMM, since you are the sole user (as Jim pointed out above), there is no big risk
2. MODI COMM for MPR QPR as an option, but this is the work I reject to do.

So if you kindly decide the way to go forward, by setting the options below:
- [x] open SPR like PRG
- [ ] open MPR QPR like a file or
- [ ] open MPR QPR like PRG, but NOEDIT
- [ ] you do the work for MPR QPR open MODI COMM as an option, if turned off (default) MODI COMM NOEDIT

@Jimrnelson If you look at [Changes](https://github.com/VFPX/GoFish/blob/master/docs/Changes.md) (I managed to create one list) V1 is from 2001-03-01 - By Peter Diotte and there seems to be no call for SPR since. :D

**Comment by Jimrnelson** [comment]
@lscheffler 

> @Jimrnelson If you look at [Changes](https://github.com/VFPX/GoFish/blob/master/docs/Changes.md) (I managed to create one list) V1 is from 2001-03-01 - By Peter Diotte and there seems to be no call for SPR since. :D

When Matt took over GF in early 2011, he ended up with what was essentially a complete re-write.  No telling now what how it worked before then,  so when he took my code from PEMEditor he may have lost something that was already working (but nobody noticed till now.)

**Comment by lscheffler** [comment]
:) So I enable SPR like PRG and that's it so far.

**Comment by nmpetkov** [comment]
@lscheffler 
Very well, this is a step in that direction! But there is a bug and now nothing opens in VFP!
The error is technical but this build should not be used until it is fixed!

`Case lcExt = 'PRG SPR '`

have to be:

`Case INLIST(lcExt, 'PRG, 'SPR')`

or

`Case lcExt $ 'PRG SPR '`

The latter is less reliable!

**Comment by lscheffler** [comment]
I go for Case `lcExt $ 'PRG SPR '`.
One char changed, 4 files to edit for verno, commited, pushed. Not very effective work.

Try again, please, new version is out

**Comment by nmpetkov** [comment]
Now SPRs open in VFP desktop.

One more place is left to change, which prevents the cursor from being positioned correctly, if anyone is interested:

![image](https://user-images.githubusercontent.com/628801/227444738-bda83dde-d01a-41d0-b38b-422ba3f66c33.png)

**Comment by lscheffler** [comment]
I strongly recommend to open a new issue for a new problem. This issue is closed, and looking at the the mail I will not see the picture. Plain text, no pics is the rule. Believe me. I only answer because the issue was open in browser.

**Comment by nmpetkov** [comment]
It is really strange the picture is not visible.
Just to be clear what is in the picture:
In gofishsearchengine.prg 

`If lcExt # 'PRG' And `

to be

`If !Inlist(lcExt, 'PRG', 'SPR', 'MPR', 'QPR') And `

I forked and will propose a PR.

**Comment by lscheffler** [comment]
This is an intentional setting in my mail reader(s). Just plain text, no pictures. This is twice as secure than antivirus, and no trace pics loaded from external servers. IOW nothing that could be active in any way. Most male-ware those days run through email.   
And I have mistaken the text for referencing #58 - and ignored it. Normally I look up the issue in github, but not in this case.   
A new issue would be visible in the issues open, so sooner or later I would check the list.

**Comment by nmpetkov** [comment]
The above mentioned can be seen in this PR
https://github.com/VFPX/GoFish/pull/75
