### ISSUE TITLE
On/off Code view section

### ISSUE THREAD

**Issue by nmpetkov** [VFPX/GoFish#86]
## 📝 Provide a description of the new feature

Navigating between rows of found search results involves visualizing the code fragment where the search was found, the so-called Code View section. Unfortunately, in many cases, at least for me, the rendering itself takes some time and slows down the work. 

This is the reason for providing the ability to easily turn this visualization on and off. In itself it is very useful and the option should be easy and quick to use. My suggestion is that it should be in the dropdown menu shown in the picture.

`Below`
`Right`
`Left`
`Off`

I think it should be quite easy to implement such an improvement.

![image](https://user-images.githubusercontent.com/628801/233370612-f3d814bc-b9cc-4b89-af62-f2d6f6bea1ac.png)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
Glad this is easy enough to implement regardless of the direction chosen.

I am unlikely to take advantage of it though, as I appreciate seeing the context in code.

As for reference to an mnx, I have a suggestion on that, which I will add as a new issue.

**Comment by lscheffler** [comment]
After looking up the code, I still come to the conclusion that there is so many stuff one will not find, since it is not documented.   
@nmpetkov It is very simple:  
The function is there all the time. There are some buttons in the very toolbar doing the job. Note: not all are visible all the time.   
![grafik](https://github.com/VFPX/GoFish/assets/27769909/f405fc70-dc13-4238-b058-d50b4ee4f080)
