### ISSUE TITLE
In the Code View window, use my colors for syntactic elements (as customized in Tools -> Options -> Editor

### ISSUE THREAD

**Issue by Jimrnelson** [VFPX/GoFish#89]
It would be nice if the Code View window showed code the same way it appears for me when I edit it:

My code:

![image](https://user-images.githubusercontent.com/81179335/233662957-0c48c7bd-071e-4bdd-bbb9-531430b8a4b8.png)

As it appears in Code View window:

![image](https://user-images.githubusercontent.com/81179335/233663147-9e239630-6bb9-4791-9bdf-3aeae68f7ce1.png)

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
As far as I know, there's nothing in Thor (meaning, tools and projects delivered by Thor) having to do with registry access.

I have no knowledge of how to get this information.

BTW, I consider this to be of low interest, even though I've been aware of it for a long, long time

**Comment by lscheffler** [comment]
Thanks for the info. I know how and what to look up in the registry. For my daily work I rely on my frame - a bit overkill here. I have no idea if I count it fun to learn it again, since dealing with registry is - odd. 

For the interest - welcome on board. It was one of my first ideas, but then it was to much boring work for that day.  But anyway, we have it on the list.

**Comment by Jimrnelson** [comment]
This feature has been implemented in Version 7, released 2024-03-08.

This feature may not always be available (for example, if black background is used) and may be disabled here:

![image](https://github.com/VFPX/GoFish/assets/81179335/8156f759-ce69-4b1e-b103-ed5f68f892b3)
