### ISSUE TITLE
In Filter Builder, unchecking Match Anywhere and Use Wildcards produces filter that will never work

### ISSUE THREAD

**Issue by TamarEGranor** [VFPX/GoFish#9]
## 📝 Provide detailed reproduction steps (if any)

1. Search the Toolbox project (in XSource) for the string "tool" with Whole word unchecked. Lots of results.
2. Click Filter
3. On the Code tab, type "#define" (without the quotes) into the Within Same Statement textbox.
4. Make sure Match anywhere and Use wildcards are unchecked.
5. Click Apply

### ✔️ Expected result

All the constant definitions would be left and everything else would be filtered out. That is, that we'd see all the search results that begin with "#define"

### ❌ Actual result

No results found

### Notes

The problem is the generated filter, which is:

(("#DEFINE"=UPPER(STATEMENT)))

That'll never be true in actual code.

Also, checking Use wildcards doesn't help, but it changes the filter. In that case you get:

((LIKE("#DEFINE",UPPER(ALLTRIM(STATEMENT,CHR(9),CHR(10),CHR(13)," ")))))

That also will never be true. In this case, the issue may be allowing the user to select Use wildcards without putting any wildcards into the expression.

**Comment by DougHennig** [comment]
If you figure out what change to make, I'll implement it.

**Comment by lscheffler** [comment]
Just for stupid me, since the form sets `SET EXACT ON` in Activate event, is there any use of `=` at all? Also the use is very limited either way, even if the operands swopped.   
@TamarEGranor    
There is a problem in your search anyway. As far as I see the problem - and the Filter is made. 
The FILTER is on the *STATEMENT* column. This is just the one single line where you found "tool". There is no result with *\#DEFINE* in it (I run through the whole set just to be sure).
For the LIKE , aside there is not return in this special case, you must enter a result that COULD be true. If you enter like *\#DEFINE*, you expect the result to be `*\#DEFINE*==UPPER(ALLTRIM(STATEMENT,CHR(9),CHR(10),CHR(13)," "))`. If one uses the `=` or the `$` operator, LIKE without wildcards is like `==` and should be kept.   
If you mean *\*\#DEFINE\** you must enter it. It would be without use for *==* or *\#DEFINE\** or *\*\#DEFINE* to add the asterix by the form.

So, my idea:
- *Use wildcards (\* and ?)* iow LIKE acts as expected
-  we should change `=` to `$`

**Comment by lscheffler** [comment]
I've gone a bit into the code. Help me out, but my English does not cover it. So, possibly all we need to do is changing the caption.

- There is a checkbox **Match anywhere** ob the Code Page of the filter form.
- If unchecked teh operator is `=` - meaning `==` since we are in EXACT ON
- if checked the operator is `$ `
- 

We define a search operand "A_String". Then we show what operator and what operand are used
| Match anywhere | Use Wildcards | Operation (result) | Operand search | Operand field |
| -- | -- | -- | -- | -- |
| 0 | 0 | = (this is: ==) | "A_String" | STATEMENT |
| 0 | I | LIKE() | "A_String" | ALLTRIM(STATEMENT,CHR(9),CHR(10),CHR(13)," ") |
| I | I | LIKE() | "\*A_String\*" | STATEMENT |
| I | 0 | $ | "A_String" | STATEMENT |

It is not very clear that *Match anywhere* is an opposite to *Exactly*, and I would expect that a wildcard search brings there own wildcards, if it means "somewhere" .

Conclusio:
The filter works as intended, only the way it is implemented is unexpected. 
So the English natives should think about better options. It's not to tricky to invert the use of *Match anywhere*, so it might be possible to use something like *Exact match*.

Note: There is a problem with filter in v6.0.007, please test after v6.0.008 is available.

**Comment by Jimrnelson** [comment]
I don't entirely follow your lengthy post, but nonetheless have this comment:

The intent of the "Match Anywhere" checkbox was to provide an opposite to "Match the beginning of the line".

"Match the beginning of the line" was my original implementation but we found that to be quite limiting.  However, it should still be easy to implement (even if I got it wrong.)

There was no interest in "Exactly" and the setting for "set exact on" should not be relevant.

**Comment by lscheffler** [comment]
Please
```
SET EXACT OFF
?'ABC'='A'
?'A'='ABC'
SET EXACT ON
?'ABC'='A'
?'A'='ABC'
```
As Tamar shows, it's implemented like **(("#DEFINE"=UPPER(STATEMENT)))** How should that compare to start of line?

**Comment by Jimrnelson** [comment]
It parameters should be in the other order with set exact off.

This also works:      ATC("#DEFINE", Statement) = 1  and is independent of Set Exact

**Comment by lscheffler** [comment]
Run the code above. Also run `HELP set exact` from command window.   
What do I care for ATC, it's not used in the filter expression we talk about.   
Since you are at v5, run the Filter in GoFish. 

---
If you don't trust my code, open commit https://github.com/VFPX/GoFish/commit/726d4aa4471df64366c5674d7f73a7ae88613869 in a new tab, download this latest version I was not involved and run this. With my comp it does not work. Do as the OP shows above.

---
But since you are unwilling to read, maybe moving pictures?   Check https://git.sonnenigel.de/root/tempproj/-/blob/main/2023-03-18_17-19-04.mkv. I will keep it open for a while

**Comment by lscheffler** [comment]
The problem is that I do not know if turning SET EXACT OFF has other side effects. Until that there is no sense in turning the = expression.
@Jimrnelson Beg your pardon, I've missed the one message and put the wrong stuff out. I'm sorry about this.

**Comment by Jimrnelson** [comment]
I have two suggestions:

[1]  Replace the checkbox with two option buttons:  "Beginning of line" and "Anywhere in line"

[2]  Replace the code for "Beginning of line" with anything that does not depend on Set Exact.   Either of the two statements below would work (and I am sure there are others):

- ```ATC("#DEFINE", Statement) = 1```
- ```"#DEFINE"==Left(UPPER(ALLTRIM(STATEMENT,CHR(9),CHR(10),CHR(13)," ")), Len ("#DEFINE"))```

**Comment by lscheffler** [comment]
My idea would be more like (in this order)
Option group:
- Exists (ATC)
- Wildcards (and if user mean ATC with wildcards user must add the asterisks, this is an app for developers ....)
- From start ( the "= left(" construction from above, only that I would swap the operands for "standard" use)

The (poorly documented) interacting checkboxes are no easy guess. I would not have groked the use without looking up the code.

Since we build the filter string anyway, I think we should simply use the string length number instead the len function, bit faster.

----
Off topic. Thanks for bringing up ATC again. I never remember this use, since a common "*C" string function is DBCS ...

**Comment by Jimrnelson** [comment]
That's incomplete, as you have ignored the (unusual) case of wildcards at the beginning of the line.

I suggest:
  - Radio button:  "Anywhere in line"
  - Radio button:  "Beginning of line"
  - Checkbox: "Use Wildcards"

This yields four distinct cases, handled conceptually like this:

NO WILDCARDS:
   - Anywhere:   ATC > 0
   - Beginning:    ATC = 1

WILDCARDS 
   - Anywhere:   LIKE('*' + Search + '*', statement)
   - Beginning:   LIKE(Search + '*', statement)
 
ATC is case insensitive, LIKE needs Upper()

**Comment by lscheffler** [comment]
I don't grok it.   
Why should the user not simple enter `"FirstWord*"` if the user likes to search that using LIKE? It's as simple as this. Again, we talk about code monkeys. One can talk about a checkbox to remove leading spaces from the (statement) field, because that's not possible with LIKE or ATC - and no regexp in filter, please.   
And that goes for *Wihtin same statement*. For the *Within Same procedure" even *=* and removing trailing spaced is rather useless.

**Comment by Jimrnelson** [comment]
Implementation of "wild cards" in V5 is that a "*" is automatically added to the beginning and end of the search phrase.  The user does not need to enter it.

You should not change this behavior; it will cause unnecessary confusion to any user who is accustomed to it.  I certainly would be confused if I entered "Select*PAL" in V6 and did not find a match because I did not add leading and trailing *s and it would take a long time to guess that they were needed.

Note that explicitly looking for matches at the beginning or ending of lines is very uncommon.  (I'm sure at some time I must have looked at the beginning of a line but cannot remember any such instance.)  Adding the *s automatically was a simple convenience chosen to handle what is by far the most frequent usage.

**Comment by lscheffler** [comment]
I see your point, but a change of the interface might change behaviour. 

Me? Alter this? We are talking a hypothetical. Me is possibly getting the `=` to work, but nothing else. Filter to *Within Same procedure" in historical records needs to be checked, since the procedures are not loaded by default - to fast to reach the 2GiB limit. I guess this has precedence to keep v5 behaviour, even over the equals problem (while this is faster to solve).

**Comment by Jimrnelson** [comment]
This checkbox has been removed.

As you noted, it will never work.

Beyond that, there's no clear explanation of what's supposed to happen if it's not checked.

Lastly, all searching in GF is "match anywhere", so it's also redundant.
